コンポーネント作成
kayac/kayac-vue-starter pull request #8
Opened 2019-01-16 02:53 UTC by yukichi-fukuzawa

ファイル名は命名規則とかわからなかったのでとりあえずこれにしています。
書き方が変とか気になる箇所があったらご指摘お願いします！

2019-01-16 03:29 UTC, tagami-mio requested changes
みました〜
コンポーネントの切り方やそれぞれのファイルの配置、ルーティングの入れ込みはみた感じおけそうです〜
３つほどコメント書きました

2019-01-16 05:14 UTC, tagami-mio requested changes
命名も合わせて修正してくれてありがとうございます！
追加でコメント一個書きました〜

2019-01-16 05:14 UTC, tagami-mio commented on src/components/RegisterForm.vue
> +  div.form-item
あ、ここ実は` .form-item`にできます。pugの場合class名だけ書いておけば自動でdiv作ってくれるんです。これ↓の `example.html`参照すると良いかも
https://qiita.com/garakuta/items/c83548c74e45838e3fe0#pug%E3%81%AE%E7%B0%A1%E5%8D%98%E3%81%AA%E7%B4%B9%E4%BB%8B

2019-01-16 05:19 UTC, aykikr commented on src/components/RegisterForm.vue
> +  div.form-item
え、ほんとだ！便利ですね…
ありがとうございます！すごく参考になります

ここだけ修正して上げておきますね〜

2019-01-16 05:34 UTC, tagami-mio commented
おけです！ありがとうございます〜
![LGTM](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCrdkPqG_vZRvwf3DycbuPeUJBMbNiP4dh6_XXUxM2BifxOvVL)

2019-01-16 05:34 UTC, tagami-mio approved these changes

2019-01-17 02:25 UTC, tagami-mio requested changes
見ました！２つほどコメント書いてます！

2019-01-17 10:22 UTC, tagami-mio requested changes
確認しましたー！いくつかコメント書きました

2019-01-17 10:22 UTC, tagami-mio commented on src/components/RegisterForm.vue
> +    p.form-warning(v-if="warningState.isEmptyCheck.name") 名前を入力してください
あ、ここのエラーメッセージ判定複数あるので、`v-else-if`で繋げて条件分岐するようにしてみてください。
https://jp.vuejs.org/v2/guide/conditional.html

2019-01-17 10:22 UTC, tagami-mio commented on src/components/RegisterForm.vue
> +    p.form-warning(v-if="warningState.isEmptyCheck.mail") メールを入力してください
こちらについても上と同じ

2019-01-17 10:22 UTC, tagami-mio commented on src/components/RegisterForm.vue
> +    isEmpty: function() {
あ、あと先ほど指摘漏れちゃってすみませんが、メソッドの場合は基本的に動詞な命名にしてください（この場合は`checkEmpty`など）。`isEmpty`のような名詞形だと、例えば中身がbooleaの値などが入っていそうな印象を受けてしまうので。

2019-01-17 10:22 UTC, tagami-mio commented on src/components/RegisterForm.vue
> +    nameLengthCheck: function() {
ここの命名も同じくですね。動詞に変えてみてください。

2019-01-17 10:22 UTC, tagami-mio commented on src/components/RegisterForm.vue
> +    mailTypeCheck: function() {
こちらについても上と同じ。

2022-07-06 07:29 UTC, closed without merging